baseURL = 'http://github.io/'
languageCode = 'en-us'
title = "Mike's notes"
theme = 'PaperMod'
paginate= 5

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
defaultTheme='dark' # auto | dark | light
ShowReadingTime=true
ShowShareButtons= true
ShowToc= true
ShowBreadCrumbs= true
ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true 
  title = "Mike's notes"
  # subtitle = "This is subtitle"
  imageUrl = "https://avatars.githubusercontent.com/u/3293?v=4"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "that's me"

[[params.profileMode.buttons]]
  name = "Posts"
  url = "posts"

[[params.profileMode.buttons]]
  name = "Tags"
  url = "tags"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.world/@mike_p"

[[params.socialIcons]]
name = "github"
url = "https://github.com/michaelp"

[markup.highlight]
#noClasses = false
# anchorLineNos = true
# codeFences: true
# guessSyntax: true
lineNos = true

# https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml